name: Deploy Application

on:
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    - name: Deploy Application
      run:
        aws deploy create-deployment --application-name Studentify \
          --deployment-group-name Backends \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
          --region ${{ vars.REGION }} \
          --file-exists-behavior OVERWRITE
