name: Deploy Application

on:
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          aws deploy create-deployment \
            --application-name Studentify \
            --deployment-group-name Backends \
            --github-location repository=TheRealGGIOVI/studentify,commitId=${{ github.sha }} \
            --region us-east-1 \
            --file-exists-behavior OVERWRITE
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
